# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Trove Data Guide
author: '<a href="https://timsherratt.org">Tim Sherratt</a>'
logo: tdg-logo.png
copyright: "2023 Australian Research Data Commons"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/wragge/trove-data-guide  # Online location of your book
  # path_to_book: docs  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  announcement: "🚧 <b>This is a working draft and will change often. Please do not cite or share!</b> 🚧"
  extra_footer: |
    <p>
    <a rel="license" href="http://creativecommons.org/licenses/by/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://i.creativecommons.org/l/by/4.0/80x15.png" /></a> This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by/4.0/">Creative Commons Attribution 4.0 International License</a>.
    </p>
sphinx:
  config:
    recursive_update: true
    #html_theme: sphinx_book_theme
    #html_theme: pydata_sphinx_theme
    html_show_copyright: true
    #templates_path:
    #  - _templates

